[package]
name = "holodex"
version = "0.1.0"
edition = "2018"
description = "A Rust wrapper of the Holodex v2 API."
repository = "https://github.com/anden3/holodex-rs"
license = "MIT OR Apache-2.0"
readme = "README.md"
keywords = ["hololive", "livestream", "api"]
categories = ["api-bindings"]


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dependencies.chrono]
version = "0.4.19"
default_features = false
features = ["std", "serde"]

[dependencies.miette]
version = "3.1.0"

[dependencies.reqwest]
version = "0.11.5"

[dependencies.serde]
version = "1.0.130"
features = ["derive"]

[dependencies.serde_json]
version = "1.0.59"

[dependencies.serde_with]
version = "1.10.0"
features = ["macros"]

[dependencies.serde-enum-str]
version = "0.2.4"

[dependencies.strum]
version = "0.22"
features = ["derive"]

[dependencies.thiserror]
version = "1.0.30"

