[package]
name = "holodex"
version = "0.2.1"
edition = "2018"
description = "A Rust wrapper of the Holodex v2 API."
repository = "https://github.com/anden3/holodex-rs"
license = "MIT OR Apache-2.0"
readme = "README.md"
keywords = ["hololive", "livestream", "api"]
categories = ["api-bindings"]


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies.tokio-test]
version = "0.4.2"

[dependencies.async-stream]
version = "0.3.2"
optional = true

[dependencies.chrono]
version = "0.4.19"
default_features = false
features = ["std", "serde"]

[dependencies.fix-hidden-lifetime-bug]
version = "0.2.4"

[dependencies.futures]
version = "0.3.17"
default-features = false
features = ["std"]
optional = true

[dependencies.itertools]
version = "0.10.1"

[dependencies.miette]
version = "3.1.0"

[dependencies.regex]
version = "1.5.4"
default-features = false
features = ["std", "perf"]

[dependencies.reqwest]
version = "0.11.5"
features = ["json"]

[dependencies.serde]
version = "1.0.130"
features = ["derive"]

[dependencies.serde_json]
version = "1.0.59"

[dependencies.serde_with]
version = "1.10.0"
features = ["macros", "chrono"]

[dependencies.serde-enum-str]
version = "0.2.4"

[dependencies.strum]
version = "0.22"
features = ["derive"]

[dependencies.thiserror]
version = "1.0.30"

[dependencies.tracing]
version = "0.1.29"

[features]
default = ["streams"]
streams = ["async-stream", "futures"]
