[package]
name = "holodex"
version = "0.1.0"
edition = "2018"
description = "A Rust wrapper of the Holodex v2 API."
repository = "https://github.com/anden3/holodex-rs"
license = "MIT OR Apache-2.0"
readme = "README.md"
keywords = ["hololive", "livestream", "api"]
categories = ["api-bindings"]


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
