[package]
name = "holodex"
version = "0.2.1"
edition = "2021"
description = "A Rust wrapper of the Holodex v2 API."
repository = "https://github.com/anden3/holodex-rs"
license = "MIT OR Apache-2.0"
readme = "README.md"
keywords = ["hololive", "livestream", "api"]
categories = ["api-bindings"]


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies.tokio-test]
version = "0.4.2"

[dev-dependencies.futures]
version = "0.3.17"
default-features = false

[dependencies.async-stream]
version = "0.3.2"
optional = true

[dependencies.chrono]
version = "0.4.19"
default_features = false
features = ["std", "serde"]

[dependencies.futures-core]
version = "0.3.17"
optional = true

[dependencies.quick-error]
version = "2.0.1"

[dependencies.regex]
version = "1.5.4"
default-features = false
features = ["std", "perf"]

[dependencies.serde]
version = "1.0.130"
features = ["derive"]

[dependencies.serde_json]
version = "1.0.59"

[dependencies.serde_with]
version = "1.10.0"
default-features = false
features = ["chrono"]

[dependencies.serde_urlencoded]
version = "0.7.0"

[dependencies.smartstring]
version = "0.2.9"
features = ["serde"]
optional = true

[dependencies.ureq]
version = "2.3.0"
features = ["json"]


[features]
default = ["streams", "sso"]
streams = ["async-stream", "futures-core"]
sso = ["smartstring"]
